use std::collections::HashMap;

use serde_json::{json, Value};

use crate::paths::ProjectPaths;
use crate::stack::StackMeta;

fn docker_name(name: &str) -> String {
    let sanitized: String = name
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '-' || c == '_' {
                c
            } else {
                '-'
            }
        })
        .collect();
    sanitized.trim_matches('-').to_string()
}

pub fn build(paths: &ProjectPaths, stack: &StackMeta, needs_secrets: bool) -> String {
    let extensions: Vec<Value> = stack.vscode_extensions.iter().map(|e| json!(e)).collect();

    let mut remote_env: HashMap<String, &str> = HashMap::new();
    remote_env.insert("EDITOR".to_string(), "code --wait");
    remote_env.insert("PROJECT_NAME".to_string(), paths.name.as_str());
    for (k, v) in &stack.remote_env {
        remote_env.insert(k.clone(), v.as_str());
    }

    let container_name = docker_name(&paths.name);
    let run_args = vec![
        "--network=bridge".to_string(),
        "--cap-drop=ALL".to_string(),
        "--security-opt=no-new-privileges".to_string(),
        format!("--name={}", container_name),
    ];

    let mut config = json!({
        "name": paths.name,
        "build": {
            "dockerfile": "Dockerfile"
        },
        "workspaceFolder": "/workspace",
        "workspaceMount": "source=${localWorkspaceFolder},target=/workspace,type=bind",
        "runArgs": run_args,
        "customizations": {
            "vscode": {
                "extensions": extensions,
                "settings": {
                    "terminal.integrated.defaultProfile.linux": "bash",
                    "security.workspace.trust.enabled": true
                }
            }
        },
        "remoteEnv": remote_env,
        "postCreateCommand": ".devcontainer/post-create.sh"
    });

    if needs_secrets {
        // Mount the directory (not the file) so atomic saves on the host don't break the inode reference
        let secrets_dir = paths.secret_file.parent().unwrap();
        let mount = format!(
            "source={},target=/run/secrets,type=bind,readonly",
            secrets_dir.display()
        );
        config["mounts"] = json!([mount]);
    }

    // Pretty-print with a header comment
    let json_str = serde_json::to_string_pretty(&config).unwrap();

    format!(
        "// {} — secure devcontainer\n// Generated by airlock v{}\n{}",
        paths.name,
        env!("CARGO_PKG_VERSION"),
        json_str
    )
}

pub fn write(paths: &ProjectPaths, stack: &StackMeta, needs_secrets: bool) -> anyhow::Result<()> {
    use std::fs;
    let content = build(paths, stack, needs_secrets);
    let dest = paths.dir.join(".devcontainer").join("devcontainer.json");
    fs::write(&dest, content)?;
    Ok(())
}
